Fixed incorrectly formatted media descriptions.
jellyfin/Swiftfin pull request #1067
Opened 2024-05-24 06:49 UTC by Alexk2309

Video descriptions often had HTML tags that weren't parsed correctly for example.

![image](https://github.com/jellyfin/Swiftfin/assets/111128610/4eaaecd1-d449-4154-bf33-2c393a66964e)

This change corrects the formatting so it now looks like

![image](https://github.com/jellyfin/Swiftfin/assets/111128610/70040e31-53f6-49a3-a27f-4f178103f028)

2024-05-24 21:46 UTC, LePips requested changes
I apologize but this work may be a lot more than you probably had anticipated. We "officially" support HTML and Markdown for item descriptions (and the server disclaimer).

*However* if you find a package that does what we need, we can use that instead.

2024-05-24 21:46 UTC, LePips commented on Swiftfin/Components/HTMLFormattedText.swift
> +    private let textView = UITextView()
Created views within `makeUIView`, not at the top level.

2024-05-24 21:46 UTC, LePips commented on Swiftfin/Components/HTMLFormattedText.swift
> +struct HTMLFormattedText: UIViewRepresentable {
I asked our team and we "officially" support HTML *and* Markdown, so this view would have to accommodate *both*.

2024-05-24 21:46 UTC, LePips commented on Swiftfin/Components/HTMLFormattedText.swift
> +    func updateUIView(_ uiView: UITextView, context: UIViewRepresentableContext<Self>) {
Change `UIViewRepresentableContext<Self>)` to just `Context`.

2024-05-24 21:46 UTC, LePips commented on Swiftfin/Components/HTMLFormattedText.swift
> +    func makeUIView(context: UIViewRepresentableContext<Self>) -> UITextView {
Change `UIViewRepresentableContext<Self>)` to just `Context`.

2024-05-24 21:46 UTC, LePips commented on Swiftfin/Components/HTMLFormattedText.swift
> +                    let fontSize = UIScreen.main.bounds.width * 0.05 // Adjust the multiplier as needed
We can't determine a font size based on the screen width. We should be using a provided system font size and the San Francisco font, not whatever serif font is being rendered.

2024-05-24 21:46 UTC, LePips commented on Swiftfin/Components/HTMLFormattedText.swift
> +        DispatchQueue.main.async {
This isn't necessary. Nothing is being updated externally that requires this view to update itself.

2024-05-24 21:46 UTC, LePips commented on Swiftfin/Components/HTMLFormattedText.swift
> +    let text: String
```suggestion
    private let text: String
```

2024-05-24 21:46 UTC, LePips commented on Swiftfin/Components/HTMLFormattedText.swift
> +    init(_ content: String) {
Change `content` to `text`.

2024-05-24 21:46 UTC, LePips commented on Swiftfin/Components/HTMLFormattedText.swift
> +        textView.widthAnchor.constraint(equalToConstant: UIScreen.main.bounds.width).isActive = true
`UITextView`s in SwiftUI are very tricky to get right. I actually just helped someone make a `UITextView` wrapper so this came at the right time. For sizing we shouldn't set constraints and instead have to go to `setContentCompressionResistancePriority`.

Here is the code that I helped the other person with, so you'll have to decipher it a bit, but it is an example of how to wrap a `UITextView` in SwiftUI. I am unsure how it works with HTML or Markdown, so you will have to test that. This work may be bigger than you expected.

- https://pastebin.com/nbiTbwcN

2024-05-24 21:46 UTC, LePips commented on Swiftfin/Components/HTMLFormattedText.swift
> +    private func converHTML(text: String) -> NSAttributedString? {
We will have to determine whether the text has HTML and then "render" it as HTML.

2024-05-25 02:23 UTC, Alexk2309 commented
> I apologize but this work may be a lot more than you probably had anticipated. We "officially" support HTML and Markdown for item descriptions (and the server disclaimer).
> 
> 
> 
> *However* if you find a package that does what we need, we can use that instead.

Hi if this is the case meaning html is supported how come the tags aren't being rendered correctly. Also does that mean i would have to find a package that converts html to markdown ? Because i know swift already supports markdown .

2024-05-25 02:29 UTC, LePips commented
My comment was that HTML and Markdown support was implemented, but that since we "support both", we need to implement support for both.

SwiftUI sadly only supports basic inline Markdown attributes (bold, italic) but not stuff like headers or bullet points. So, technically, even Markdown needs proper implementation.

2024-06-08 02:35 UTC, LePips commented
I'm actually going to have to think about this a bit more. While we/other clients "officially" support HTML, I think that this would be too large of a hassle for all clients to support and would advocate for stripping HTML on the server.

2024-06-13 02:05 UTC, chickdan commented
I tested the solution in [this SO post](https://stackoverflow.com/questions/56892691/how-to-show-html-or-markdown-in-a-swiftui-text) (`NSAttributedString`) and it worked. `Text` can also handle Markdown natively so maybe if there was a function to detect html (regex aught to do it) and return the overview as `NSAttributedString` otherwise return as a `String`. That would save having to use `UIVIewRepresentable` to make a `UITextView` and resolve the issue of supporting both formats.

2025-07-20 04:09 UTC, LePips commented
I'm closing this in favor of just using an `AttributedString` solution.

2025-07-20 04:09 UTC, closed without merging