[WIP] update swiftfin tvos signin
jellyfin/Swiftfin pull request #1113
Opened 2024-06-15 06:25 UTC by Isaiah-Hamilton

## Changes made

Updated the swiftfin tvos signin view

## Before

![Simulator Screenshot - Apple TV 4K (3rd generation) - 2024-06-15 at 02 17 00](https://github.com/jellyfin/Swiftfin/assets/70828596/2217a17a-b0a8-4193-859e-e57c5a6a3a4e)

## After

![Simulator Screenshot - Apple TV 4K (3rd generation) - 2024-06-15 at 02 08 41](https://github.com/jellyfin/Swiftfin/assets/70828596/42794d68-548d-4b4d-9c07-b22123b4f54a)
## Feedback

Let me know which one is best and what you think.

2024-06-28 18:03 UTC, LePips requested changes

2024-06-28 18:03 UTC, LePips commented on Swiftfin tvOS/Views/UserSignInView/UserSignInView.swift
> +                VStack {
Thank you for fixing the buttons, but this needs to be in a `HStack` like before. This is a deliberate design decision for these being different sections, and they should be equally sized. Additionally, the public user section can be of any size and requiring to scroll through them isn't desirable.

2024-12-12 21:30 UTC, JPKribs commented
Hi @Isaiah-Hamilton,

I hope you’re doing well! I just wanted to check in to see if you’re still interested in working on this. I’ve been revisiting some tvOS features recently, and I think there’s some potential for refining this `View`. If you’re still keen on handling it, I completely respect that and don’t want to overstep at all.

However, if you’re a bit busy or prefer someone else to take it on, I’d be happy to help out or even pick it up from here! This is the latest version I was working on based on @LePips feedback:

![Simulator Screenshot - Apple TV 4K (3rd generation) - 2024-12-12 at 13 44 59](https://github.com/user-attachments/assets/16ff06be-da13-45ae-8fc2-6021da51105b)

I'd be happy to share this code as well!

Let me know your thoughts! 😊

2024-12-17 16:09 UTC, Isaiah-Hamilton commented
@JPKribs I'm a little to busy at the moment to work on this, but I would be happy to pass this over to someone else. Though I would still like to be kept in the loop/have to some input on somethings. So far what you have is great, and think we should go based on what you have currently.

2024-12-17 19:56 UTC, JPKribs commented
> @JPKribs I'm a little to busy at the moment to work on this, but I would be happy to pass this over to someone else. Though I would still like to be kept in the loop/have to some input on somethings. So far what you have is great, and think we should go based on what you have currently.

Sounds good! Thanks for getting the ball rolling. I have my branch of this here: https://github.com/jellyfin/Swiftfin/pull/1365

Let me know if you have any feedback! I found that the `ConnectToServerView` and `UserSignInView` were both build on the same layout so my primary change from here is to reuse the same layout for both.

2024-12-19 21:37 UTC, JPKribs commented
This work has been merged in via https://github.com/jellyfin/Swiftfin/pull/1365, so I am going to close this out.

Thank you again for getting the ball rolling with this SignIn cleanup, @Isaiah-Hamilton!

2024-12-19 21:37 UTC, closed without merging