[iOS] Playback Quality - Learn More
jellyfin/Swiftfin pull request #1316
Opened 2024-11-17 21:33 UTC by JPKribs

### Summary
This is a pretty small change. It's just adding Learn More descriptions to Playback quality since we had a TODO for it and it's one of our more confusing sections.

I also updated the LearnMoreButton to have an optional footer input. This way, any Footer+LearnMore inputs are formatted the same instead of recreating the spacing each time.

<details>
<summary>Main</summary>
<img src="https://github.com/user-attachments/assets/535ca00e-a1c5-4e7c-88a5-48feb55a021f" alt="Screenshot 1" width="400">
</details>

<details>
<summary>Bitrate</summary>
<img src="https://github.com/user-attachments/assets/5d651492-6553-411f-aa34-172d90eeb319" alt="Screenshot 2" width="400">
</details>

<details>
<summary>Test</summary>
<img src="https://github.com/user-attachments/assets/5bf1f0c4-cc8e-4808-b2b4-ad5275cfd9f9" alt="Screenshot 3" width="400">
</details>

<details>
<summary>Profiles</summary>
<img src="https://github.com/user-attachments/assets/ceec443c-cf63-4696-a7dd-66efebccb6f0" alt="Screenshot 4" width="400">
</details>

2024-11-17 22:34 UTC, JPKribs commented
I think this is almost ready. My only issue is the alignment for the text on row 2 or greater. It wants to center it and I can't seem to figure out how to get it to both have AccentColor for LearnMore AND be Leading Alignment.

2024-11-18 01:14 UTC, JPKribs commented
Here is what tvOS looks like. I'm not sure if there is a better way to handle focus but I think this *looks* good. Focus, I'm open to feedback for how this should work:

![Simulator Screenshot - Apple TV 4K (3rd generation) - 2024-11-17 at 18 13 02](https://github.com/user-attachments/assets/b142b25b-1b62-42e0-892c-397ceac80c64)
![Simulator Screenshot - Apple TV 4K (3rd generation) - 2024-11-17 at 18 13 06](https://github.com/user-attachments/assets/bea20043-f434-42db-b50d-5816277aea65)
![Simulator Screenshot - Apple TV 4K (3rd generation) - 2024-11-17 at 18 13 59](https://github.com/user-attachments/assets/c39c09f0-c2c1-4fb8-a382-b03392d71ece)

2024-11-18 02:48 UTC, LePips requested changes
Don't make any changes to `LearnMoreButton` since that should just hold a button. While in iOS Settings it sometimes does have the `Learn More...` as a suffix to the description, I would want it to just always be leading aligned below the original description.

So the footers would look something like the following to get the desired layout:
```swift
VStack(alignment: .leading) {
    L10n.bitrateTestDisclaimer.text

    LearnMoreButton(
        L10n.bitrateTest
    ) {
        TextPair(
            title: L10n.testSize,
            subtitle: L10n.bitrateTestDescription
        )
    }
}
```

In order to get the desired affect you want you would have to make something like an `AttributedString/NSAttributedString` but that is a bit more work.

Edit: I started writing this before you fixed it with `buttonStyle(.plain)`, but I would still personally want the layout I describe.

2024-11-18 02:49 UTC, LePips commented
I am unsure of what to do on tvOS, as I don't know how other apps have a `Learn More` UX. We shouldn't necessarily just copy from iOS.

2024-11-18 03:00 UTC, JPKribs commented
In an earlier version I had of this, I had the regular footer and the button in a Vstack. I don't think it was bad so if we like that layout I can move back to that. My primary reason for moving away from it was that is wasn't the same as the iOS settings.

For tvOS, maybe the solution is a single button at the end of the list for 'details' or something like that with all of the buttons that need context in a single view. Let me roll this back to an earlier version so we can work from a closer-to-main place!

2024-11-18 03:15 UTC, JPKribs commented
> I am unsure of what to do on tvOS, as I don't know how other apps have a `Learn More` UX. We shouldn't necessarily just copy from iOS.

I think "Learn More..." isn't the best text to go there but we're really only going to need additional information in settings for tvOS. In this case, we could have it popup in a sheet with sections for the items that might need some additional detail?

![Simulator Screenshot - Apple TV 4K (3rd generation) - 2024-11-17 at 20 13 47](https://github.com/user-attachments/assets/fa4b705b-b03c-4ffc-82d1-de71c7367a24)

2024-11-20 22:00 UTC, LePips requested changes
I think the idea for tvOS works now, but I can see issues if it is too large and requires scrolling. We can see if other solutions work better in the future.

2024-11-20 22:00 UTC, LePips commented on Swiftfin/Views/SettingsView/PlaybackQualitySettingsView.swift
> +                        LearnMoreButton(L10n.bitrateTest) {
`Learn More` should be for more detail on multiple items or for a single section that requires a lot more description. This specific section can be described concisely, so we don't need a `Learn More` for it.

2024-11-21 18:58 UTC, JPKribs commented
> I think the idea for tvOS works now, but I can see issues if it is too large and requires scrolling. We can see if other solutions work better in the future.

I have your changes in. One idea I was thinking of was expanding out ScrollIfLargerThanContainerModifier to have a toggle for 'autoScroll' then have it just scroll through a view with this enabled. This way, if an item on the left was too large, this would treat it as a scrollview and automatically scroll through the content. This is my working version which 'works' but also scrolls way to quickly then never resets back to the top:

```
struct ScrollIfLargerThanContainerModifier: ViewModifier {

    @State
    private var contentSize: CGSize = .zero
    @State
    private var layoutSize: CGSize = .zero

    let padding: CGFloat
    let autoScroll: Bool

    func body(content: Content) -> some View {
        AlternateLayoutView {
            Color.clear
                .trackingSize($layoutSize)
        } content: {
            ScrollViewReader { proxy in
                ScrollView {
                    VStack {
                        content
                            .trackingSize($contentSize)
                        Color.clear
                            .frame(height: 0)
                            .id("BottomAnchor")
                    }
                }
                .frame(maxHeight: contentSize.height >= layoutSize.height ? .infinity : contentSize.height)
                .scrollDisabled(contentSize.height < layoutSize.height)
                .scrollIndicators(.never)
                .onChange(of: contentSize) { _, newSize in
                    if autoScroll && newSize.height >= layoutSize.height {
                        withAnimation {
                            proxy.scrollTo("BottomAnchor", anchor: .bottom)
                        }
                    }
                }
            }
        }
    }
}
```

If you like this idea, I can work on it more or make it it's own ViewModifier since the overlap might not make sense to include on this existing ViewModifier.

2024-11-21 19:07 UTC, JPKribs commented
If we aren't worried about the tvOS size quirks, I think this should be ready to go from my end!

2024-11-21 20:47 UTC, LePips approved these changes
Looks great!

2024-11-21 20:47 UTC, merged