Change to utilize image API
jellyfin/Swiftfin pull request #225
Opened 2021-11-12 13:54 UTC by PangMo5

- Change the url image format to webp

2021-11-12 14:13 UTC, LePips requested changes

2021-11-12 14:13 UTC, LePips commented on JellyfinPlayer.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 4BHXT8RHFR;
Remove your development team

2021-11-12 14:14 UTC, PangMo5 commented on JellyfinPlayer.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 4BHXT8RHFR;
Ah, I forgot that again. lol

2021-11-12 14:31 UTC, PangMo5 commented
Oh, it seems that webP support is not available on tvOS.
I'll go back to jpg.

2021-11-12 18:31 UTC, LePips approved these changes

2021-11-13 22:16 UTC, acvigue approved these changes

2021-11-13 22:16 UTC, acvigue commented
Sorry - would've reviewed this earlier. I was at a college tour.

2021-11-13 22:16 UTC, merged

2021-11-13 22:19 UTC, PangMo5 commented
np 😆