iOS - Add known public users to login screen
jellyfin/Swiftfin pull request #473
Opened 2022-07-10 16:38 UTC by daullmer

Add public users to login screen

https://user-images.githubusercontent.com/16425113/178153693-70f3f270-8a51-4b71-bdf1-ac4612a7b6b6.mov

2022-07-10 23:12 UTC, LePips requested changes
Thank you for your contribution! Please see comments.

2022-07-10 23:12 UTC, LePips commented on Shared/Generated/Strings.swift
> +  internal static var knownUsers: String { return L10n.tr("Localizable", "knownUsers") }
Change the original localizable string to "Public Users", as "Known" means something different.

2022-07-10 23:12 UTC, LePips commented on Shared/Views/UserLoginCellView.swift
> +					.padding(.leading, 4.0)
Please remove this padding.

2022-07-10 23:12 UTC, LePips commented on Shared/Views/UserLoginCellView.swift
> +			let url = URL(string: "\(server)/Users/\(userId)/Images/Primary?width=200&tag=\(imageTag)&quality=90")
Please use the API and these `nil` checks will not be necessary either:
```swift
ImageAPI.getUserImageWithRequestBuilder(userId: userId,
                                        imageType: .primary,
                                        width: 200,
                                        quality: 90)
```

2022-07-10 23:39 UTC, LePips requested changes

2022-07-10 23:39 UTC, LePips commented on Swiftfin/Views/UserSignInView.swift
> +				if !viewModel.users.isEmpty {
Please put these below the original text fields. This is dynamic, there may be no public users or many public users and will push down the main part of the view and mirrors the way local servers are handled.

2022-07-11 05:54 UTC, daullmer commented
Thank you very much for your comments! I will change the things you requested and then work on the refresh functionality like in `ConnectToServerView`

2022-07-11 15:53 UTC, LePips requested changes
Looks great! Just a couple small things and something I was wrong about.

2022-07-11 15:53 UTC, LePips commented on Swiftfin/Views/PublicUserSignInCellView.swift
> +				Text(user.name ?? "")
The "--" fallback should be used here when shown to the user.
```suggestion
				Text(user.name ?? "--")
```

2022-07-11 15:53 UTC, LePips commented on Swiftfin/Views/PublicUserSignInCellView.swift
> +					Image(systemName: "person.circle")
I apologize and was incorrect, `.resizable()` actually is required here.

2022-07-11 16:18 UTC, LePips commented
Would you like to handle the linting errors? I'm fine with leaving it and catching it later on.

2022-07-11 16:34 UTC, merged